### PR TITLE
Docker cleanup

### PR DESCRIPTION
**Pull request by joshmoore**
Following on from http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2015-January/003121.html, this PR cleanups, removes, and renames some of the docker files in preparation for a more general use of this repository. A few minor changes that I had locally have also been included to simplify the testing of these changes. Individual commits contain the reasons behind the changes. 

The README should be updated with the intent of each subdirectory before this is merged.

/cc @manics @hajaalin @hadim

### CODE REVIEW

**Comment by manics** [comment]
I'm begining to have doubts about the wisdom of stuffing all build environments into one image, thought difficult to tell until we actually start using it.

**Comment by joshmoore** [comment]
@manics: yeah, there's certainly a balance between too many Dockerfiles and too complex Dockerfiles. If we want more infrastructure style images, perhaps we move those to infra?

Regardless, I would like to get https://github.com/joshmoore/docker/commit/0581197f54f9c07418a74cb4a53a713c54642b32 into the wild for testing Ice. Shall I pull it out of this or are you generally ok with the PR?

**Comment by manics** [comment]
No objections, just thought I'd give you a heads up on my thoughts. Trying a build now....

**Comment by manics** [comment]
> The README should be updated

Are you still planning to do this?

Also any thoughts on updating the conda image ( #4 )

**Comment by joshmoore** [comment]
#4 cherry-picked and pushed.

**Comment by joshmoore** [comment]
Done. README is still missing and I'll still need to test each of the end products (bftools, box, build, process). Hope I can automate that at some point. /cc @sbesson

**Comment by manics** [comment]
First step is to get a Jenkins Docker node up ...

**Comment by joshmoore** [comment]
Jotting down some notes here while we await the new node... ( I can feel it. Very soon! )

I can picture a workable hierarchy of images:

 * omero-ubuntu: single conda-based image usable in production
   * omero-ubuntu-multienv: multiple condas also with build dependencies
 * omero-centos: single centos support usual in production
   * omero-centos-multienv: multiple centos support from @manics also with build dependencies

I would think @hajaalin and @hadim's "server" and "web" images could come from either of those. Also, I think if many of the commands from each of your repos were added to http://github.com/ome/omego, then in general, Dockerfiles would get much simpler.

**Comment by hadim** [comment]
I would be ahppy to use omero-ubuntu or omero-centos as base image for my omero-server and omero-web.

I also added in Dockerfile init.sh and start.sh scripts to do the dirty job on docker build and start. But I agree that it would really nice to add them to omego.

Basically my needs are:
- creating, only of it does not exist (add force parameter?), pgsql database
- run some `bin/omero config set` command to setup host, port and data dir on the fly when a container start

For my omero-web if you see something which could be put in common, tell me. I think omero-web is very generic and maybe this image could go in https://github.com/ome repo. What do you think ?

About docker-compose (formerly called fig) I am still limited by some features not included. I think I will wait a bit more before using it. See here https://github.com/hadim/docker-omero#fig-support for more details.
 
I am still not happy with data dir management. I don't know the best way to manage it. Using a volume container seems to be the clever approach. However data dir can become huge in production so I need to find a way to easly move a volume container to another partition/disk/computer and I don't know how docker can handle that...

**Pull request merged**
