### PR TITLE
Omero server prerequisites with omego

### PR DESCRIPTION
**Pull request by manics**
Initial attempt at a docker image that can be used to easily deploy a user-selected OMERO.server. Arguments are appended to the omego command line. Pass `""` to disable OMERO installation.
```
docker run -d omero-server-prereq
```
downloads and runs OMERO.server-5.1.1-ice35-b43.zip
```
docker run -d omero-server-prereq https://downloads.openmicroscopy.org/omero/5.1.0/artifacts/OMERO.server-5.1.0-ice35-b40.zip
```
installs OMERO.server-5.1.0-ice35-b40.zip
```
docker run -d omero-server-prereq --branch OMERO-5.1-merge-build
```
installs the 5.1 merge build

For manual server installation:
```
CID=$(docker run -d -e "SERVICE_NAME=dns-name" omero-server-prereq "")
echo $CID
docker exec $CID /omero-setup https://downloads.openmicroscopy.org/omero/5.1.1/artifacts/OMERO.server-5.1.1-ice35-b43.zip
```
Note `ENTRYPOINT` has been removed in omero-conda- it breaks `CMD` in downstream Dockerfiles and the default `ubuntu:14.04` one seems to work fine.

This image currently has full ssh access and full sudo rights for the `omero` user. This should be fixed in future.

### CODE REVIEW

**Comment by joshmoore** [comment]
Why the `-prereq` suffix on the name?

**Comment by manics** [comment]
To indicate it doesn't include the server. I couldn't think of a better name, suggestions?

**Comment by manics** [comment]
Note I'm going to try and set the entrypoint so that it installs a server by default but can be overridden

**Comment by joshmoore** [comment]
+1 on the entrypoint. Guess I'm mostly worried about consumers understanding what this is an when it should be used. Simply having an `omero-server`, to me, is a makes sense. Could this thing be the "base" for other images too?

**Comment by manics** [comment]
Description updated. At the moment we probably don't want anyone using this image, and I'm not sure whether having a combined produciton and test image is feasible. omero-server-<something to indicate its currently for testing>?

**Comment by joshmoore** [comment]
Description looks good (like the idea!). But perhaps `omero-deploy`? or some form of `omego`?

**Comment by manics** [comment]
How's this?

**Comment by joshmoore** [comment]
Yup, starting to look like another quite useful (if slightly overlapping) member for the `omero-install`/`omego` ecosystem.

**Comment by manics** [comment]
Eventually omero-install should use omego.

**Comment by joshmoore** [comment]
Tested the state of this with 3842. If you don't have anything else coming, big :thumbsup:

**Comment by manics** [comment]
I've got a few more changes to make it play nicely with an existing PGDATA dir

**Comment by manics** [comment]
I'll test this a bit more, but I think it's done. See the README

**Comment by manics** [comment]
Any objections to merging this since it's been running for a while, with any future changes in another PR?

**Comment by joshmoore** [comment]
Seems fine. Hook up to docker hub?

**Comment by manics** [comment]
I'll add it to the todo list. Did you see http://docs.travis-ci.com/user/docker/ ? We might be able to get travis to do our docker merge builds (docs say it can push images, but it's not clear how it's configured)

**Comment by joshmoore** [comment]
Yup, saw that. Happy to do the testing via travis and say only build master on hub, but probably just want one "trusted" build server.

**Pull request merged**
