### PR TITLE
If ~omero/OMERO.server exists don't install a new server

### PR DESCRIPTION
**Pull request by manics**
This should only occur when restarting an existing container. Fixes https://github.com/ome/ome-docker/issues/15

### CODE REVIEW

**Comment by joshmoore** [comment]
```
root     30457  0.0  0.0  17976  3016 ?        S    10:34   0:00       /bin/bash /omero-setup
root     30520  0.0  0.0  46632  2700 ?        S    10:34   0:00         su - omero -c /home/omero/OMERO.server/bin/omero admin start
docker   30529 13.0  1.7 255972 69856 ?        Ssl  10:34   0:00           python /home/omero/OMERO.server/bin/omero admin start
```

on restart. :thumbsup:

**Comment by manics** [comment]
Rebased and added commit c3fabd0 which installs https://github.com/ome/omego/archive/master.zip instead of the latest omego release (can revert once omego is stable enough for use by everyone else).

**Comment by joshmoore** [comment]
```
$ docker-machine create --driver virtualbox --virtualbox-memory 4096 --virtualbox-disk-size 100000 ome-docker
$ time build.sh
...
Downloading ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/systems/texlive/tlnet/archive/formlett.tar.xz did not succeed.
Installation failed.
Rerunning the installer will try to restart the installation.
Or you can restart by running the installer with:
  install-tl --profile installation.profile [EXTRA-ARGS]
./install-tl: Writing log in current directory: /opt/install-tl-20151105/install-tl.log
The command '/bin/sh -c curl -L http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz |    tar -zxf - &&   cd install-tl-*/ &&     ./install-tl -profile /opt/texlive.profile &&       ln -s /opt/texlive/texmf-var/fonts/conf/texlive-fontconfig.conf                 /etc/fonts/conf.d/09-texlive.conf &&    fc-cache -rsfv' returned a non-zero code: 1
Build failure: omero-build-c6-multienv

real    106m3.638s
# Second run
...
real    135m50.381s
user    0m3.546s
sys     0m0.842s
```

In other words, our build time for the whole repo (by-the-by) is currently quite a few hours:
```
openmicroscopy/omero-unittest            latest              d634fc8ca4c6        13 minutes ago      1.411 GB
openmicroscopy/omero-process             latest              04bc11d8a4aa        14 minutes ago      1.421 GB
openmicroscopy/omero-in-a-box            latest              5f6a12d3c028        14 minutes ago      1.51 GB
openmicroscopy/omero-deploy              latest              453078e6f66a        16 minutes ago      1.547 GB
openmicroscopy/omero                     latest              523a98454b84        20 minutes ago      1.945 GB
openmicroscopy/tarantula                 latest              7fa7a97f283f        29 minutes ago      1.391 GB
openmicroscopy/omero-build-c6-multienv   latest              72a6c82f289d        42 minutes ago      4.189 GB
openmicroscopy/omero-conda               latest              a9962d0422e0        3 hours ago         1.377 GB
openmicroscopy/omero-ssh                 latest              ef5ec64a0b9d        4 hours ago         194.2 MB
openmicroscopy/bftools                   latest              79d4b307a90c        4 hours ago         674.9 MB
openmicroscopy/data                      latest              6b32c1c4b58f        4 hours ago         1.11 MB
openmicroscopy/postgresql                latest              ccde55ce6989        4 hours ago         522.7 MB
```

and while I'm reviewing the whole repo:

```
digraph Dockerfiles {
  "busybox" -> "openmicroscopy/data";
  "felix/postgresql" -> "openmicroscopy/postgresql";
  "centos:centos6" -> "openmicroscopy/omero-build-c6-multienv";
  "centos:centos6" -> "openmicroscopy/tarantula";
  "centos:centos7" -> "openmicroscopy/omero-ssh";
  "openmicroscopy/omero-conda" -> "openmicroscopy/omero";
  "openmicroscopy/omero-conda" -> "openmicroscopy/omero-deploy";
  "openmicroscopy/omero-conda" -> "openmicroscopy/omero-in-a-box";
  "openmicroscopy/omero-conda" -> "openmicroscopy/omero-process";
  "openmicroscopy/omero-conda" -> "openmicroscopy/omero-unittest";
  "ubuntu:14.04" -> "openmicroscopy/omero-conda";
  "java:7" -> "openmicroscopy/bftools";
}
```

**Comment by joshmoore** [comment]
docker run -d ... docker stop ... docker start works fine.

```
root@d2a1395cd033:~# omego version
UNKNOWN
```

**Comment by manics** [comment]
I've given up on the full repo build, we should rethink it.

**Comment by joshmoore** [comment]
Which do you consider the full repo build? c6-multienv?

**Comment by manics** [comment]
I meant full-repo as in building everything in this repo in one go.

Is anyone using c6-multienv? If not perhaps we should rethink the multienv concept with docker (and move to c7 in the interests of keeping things simple?), especially if we take advantage of the new http://docs.docker.com/engine/reference/builder/#arg

**Comment by joshmoore** [comment]
> I meant full-repo as in building everything in this repo in one go.

i.e. you'd move to one repo per dockerfile?

> Is anyone using c6-multienv?

Minimally all devspaces. But there's certainly potential for making use of `ARG`

**Comment by manics** [comment]
I was more thinking of not having to rebuild the entire repo with each change, or alternatively doing parallel builds (e.g. if we were to enable travis).

Any objections to merging?

**Comment by joshmoore** [comment]
> I was more thinking of not having to rebuild the entire repo with each change, or alternatively doing parallel builds (e.g. if we were to enable travis).

Oh agreed. I don't regularly do that, but was working on a new docker-machine and thought it worth trying.

> Any objections to merging?

Nope.

**Pull request merged**
