### PR TITLE
Add WND-CHARM Docker image

### PR DESCRIPTION
**Pull request by manics**
Part of the work on testing WND-CHARM in the IDR. Don't merge yet.

@colettace Can you remind me how to run the tests?

### CODE REVIEW

**Comment by colettace** [comment]
@manics you mean this?
```
cd tests/pywndcharm_tests
python -m unittest discover
```

**Comment by manics** [comment]
Does this look familiar?

```
[wndcharm@b7ddf323bff3 pywndcharm_tests]$ python test_FeatureVector.py
Traceback (most recent call last):
  File "test_FeatureVector.py", line 221, in <module>
    from wndcharm.FeatureSpace import FeatureSpace
  File "/usr/lib64/python2.7/site-packages/wndcharm-0.9.11-py2.7-linux-x86_64.egg/wndcharm/FeatureSpace.py", line 55, in <module>
    class FeatureSpace( object ):
  File "/usr/lib64/python2.7/site-packages/wndcharm-0.9.11-py2.7-linux-x86_64.egg/wndcharm/FeatureSpace.py", line 68, in FeatureSpace
    channel_col_finder = re.compile(r'(?P<path>.*?)?\{(?P<opts>.*?)?\}')
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

**Comment by colettace** [comment]
what does <code>cat /etc/redhat-release</code> and <code>python --version</code> say?

**Comment by manics** [comment]
```
[wndcharm@b7ddf323bff3 ~]$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[wndcharm@b7ddf323bff3 ~]$ python --version
Python 2.7.5
```

Installation steps are all in https://github.com/ome/ome-docker/pull/27/files#diff-6f1358368f9abe505c8ef01514b8e886

**Comment by colettace** [comment]
That error does look familiar:

http://stackoverflow.com/questions/5869650/python-regex-strange-behavior

We got it on Linux when using Python 2.6, so we stopped supporting. I thought it was a 2.6 vs. 2.7 problem but now I see earlier versions of Python 2.7 are also susceptible.

Well, upgrading Python to the latest version should fix it, but maybe I can look into changing it so it will be backwards-compatible?

**Comment by manics** [comment]
I thought I'd try Ubuntu 14.04. It has the same Pytohn version (2.7.5) but appears to more or less work. A few tests are failing, but doesn't look too bad.

**Comment by joshmoore** [comment]
cc: @simleo in case you're interested.

**Comment by simleo** [comment]
Thanks @joshmoore, added https://github.com/simleo/pydoop-features/issues/30

**Pull request closed without merging**
