### PR TITLE
Improve user experience with omero-deploy

### PR DESCRIPTION
**Pull request by joshmoore**
* Include "openmicroscopy/" in readme.
 * Use bash shell for history support on ssh.

### CODE REVIEW

**Comment by manics** [comment]
Have you tried this with an existing populated `/data`? I think https://github.com/ome/ome-docker/blob/master/omero-deploy/omero-setup may fail if there's already a server in `/home/omero/`

**Comment by manics** [comment]
Also doesn't work with an empty /data (`WORKDIR /home/omero` in `omero-conda`, but now `/home/omero` doesn't exist if `/data` is an empty external volume)

**Comment by manics** [comment]
How about merge #13 rebase chsh and README updates, and I'll figure something out for running omero (e.g. try and symlink the `OMERO.server/var/logs/` to `/data`). Or we start work on a proper production multicontainer image, marks logs as a volume, and run read-only containers.

**Comment by joshmoore** [comment]
Pushed. Leaving /home/omero to you.

**Comment by manics** [comment]
One more`openmicroscopy/` needed as a result of the rebase: ` docker run -d -e SYSTEM_PASSWORD=abc -e OMERO_PASSWORD=def omero-deploy`

**Comment by joshmoore** [comment]
Pushed

**Comment by manics** [comment]
:+1:

**Comment by manics** [comment]
See also #4225 https://github.com/manics/openmicroscopy/commit/558f0a28bfbd71dc7f35ff8519971b3fd660e8da

**Pull request merged**
